import Head from 'next/head'
import Login from '../components/Login'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full flex h-screen justify-center items-center">
        <div className="space-y-3">
          <h1 className="text-3xl font-bold bg-gradient-to-r from-cyan-500 to-blue-500 text-sky-100 px-6 py-4">
            Ingresa tus datos para votar
          </h1>
          <Login />
        </div>
      </main>
    </div>
  )
}
